services:
  web:
    image: nginx:alpine
    networks:
      macnet:
        ipv4_address: 192.168.1.100

networks:
  macnet:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
