services:
  web1:
    image: nginx:alpine
    network_mode: host
    environment:
      - NGINX_PORT=8080
  web2:
    image: nginx:alpine
    network_mode: host
    environment:
      - NGINX_PORT=8080
