---
- name: Quick connectivity check
  hosts: all
  gather_fact: false
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is reachable"
