---
- name: Platform-specific package installation
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install packages on Debian
      ansible.builtin.apt:
        name: vim
        state: present
      when: ansible_os_family = "Debian"

    - name: Install packages on RedHat
      ansible.builtin.yum:
        name: vim
        state: present
      when: ansible_os_family == "RedHat"
